typography_spectrum: 0.49293051939457655
color:
  brandStrength: 0.5099346700590104
  lightness: 0.23611184186302125
  saturation: 0.009646255057305098
  rhythmicContrast: 0.9382617608644068
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.5952105142641813
author:
  name: Clinton Cohagan
  email: ccohagan@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fccafd87-a566-4b57-9775-bb4caf166c1d.jpg
name: the cohagans
title: a family living life together
